Imports System.IO
Imports GSM.Node.Api
Imports Microsoft.AspNetCore.Builder
Imports Microsoft.AspNetCore.Http
Imports Microsoft.Extensions.DependencyInjection
Imports Microsoft.Extensions.Hosting
Imports Microsoft.Extensions.Logging
Imports System.Text.Json
Imports System.Text.Json.Serialization

' ============================================================
'  GSM Node Service - Entry Point
'
'  Startup sequence:
'    1. Read configuration (port, auth token, data directory)
'    2. Register all services into the DI container
'    3. Initialise local SQLite database
'    4. Register all REST API endpoints
'    5. Start the ASP.NET Core HTTP server
'
'  Running as a service:
'    Windows: install with `sc create` or the manager push-install
'    Linux:   systemd unit file (generated by manager on deploy)
'
'  Configuration is read from (in priority order):
'    1. Environment variables  (GSM_NODE_PORT, GSM_NODE_TOKEN, ...)
'    2. nodesettings.json in the working directory
'    3. Built-in defaults
' ============================================================

Module Program

    Sub Main(args As String())
        ' CreateBuilder sets up the ASP.NET Core host with sensible
        ' defaults: built-in DI container, configuration system,
        ' logging to console, and Kestrel HTTP server.
        Dim builder = WebApplication.CreateBuilder(args)

        ' ---- Run as Windows Service or Linux systemd if not interactive ----
        ' When running interactively (debugging) this is a no-op.
        ' When installed as a service, this hooks into the service lifecycle.
        If Not Environment.UserInteractive Then
            builder.Host.UseWindowsService()
            builder.Host.UseSystemd()
        End If

        ' ---- Configuration ----
        ' Pull node settings from environment variables or config file.
        ' We do this before registering services so we can validate early.
        Dim config = NodeConfiguration.Load(builder.Configuration)

        ' ---- JSON serialisation ----
        ' Configure how our request/response objects are serialised.
        ' We use camelCase to match standard JSON conventions.
        builder.Services.ConfigureHttpJsonOptions(
            Sub(opts)
                opts.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                opts.SerializerOptions.DefaultIgnoreCondition =
                    JsonIgnoreCondition.WhenWritingNull
                opts.SerializerOptions.Converters.Add(
                    New JsonStringEnumConverter(JsonNamingPolicy.CamelCase))
            End Sub)

        ' ---- Register core node services into DI ----
        ' DI (Dependency Injection) means we declare what each class
        ' needs, and the framework creates and passes them automatically.
        ' AddSingleton = one shared instance for the whole app lifetime.
        ' AddScoped    = one instance per HTTP request.
        ' AddTransient = new instance every time it's requested.

        ' Single shared instance of each core service.
        builder.Services.AddSingleton(config)
        builder.Services.AddSingleton(Of NodeDatabase)()
        builder.Services.AddSingleton(Of ProcessManager)()
        builder.Services.AddSingleton(Of RingBufferStore)()
        builder.Services.AddSingleton(Of RconClientManager)()
        builder.Services.AddSingleton(Of InstallRunner)()

        ' Logging - writes to console (and Windows Event Log when running as a service)
        builder.Services.AddLogging(
            Sub(logging)
                logging.AddConsole()
                If Not Environment.UserInteractive Then
                    logging.AddEventLog()   ' Windows only - no-op on Linux
                End If
            End Sub)

        ' ---- Build the application ----
        Dim app = builder.Build()

        ' ---- Authentication middleware ----
        ' Every request (except GET /api/version) must carry the bearer token.
        ' This runs before any endpoint handler sees the request.
        app.Use(Function(context, [next]) AuthenticateRequestAsync(context, [next], config))

        ' ---- Initialise database and services ----
        ' This runs synchronously before the server starts accepting requests.
        Dim db = app.Services.GetRequiredService(Of NodeDatabase)()
        db.Initialise()

        Dim processManager = app.Services.GetRequiredService(Of ProcessManager)()
        processManager.Initialise()   ' Re-attaches to any processes running before a node restart

        ' ---- Register all API endpoints ----
        InstanceEndpoints.Register(app)
        InstallEndpoints.Register(app)
        SystemEndpoints.Register(app)

        ' ---- Version endpoint (unauthenticated) ----
        app.MapGet("/api/version", Function() New NodeVersionResponse With {
            .ApiVersion = "1.0",
            .NodeVersion = If(GetType(Program).Assembly.GetName().Version?.ToString(), "0.0.0"),
            .RuntimeVersion = System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription,
            .Os = If(OperatingSystem.IsWindows(), "Windows", "Linux"),
            .Hostname = Environment.MachineName
        })

        ' ---- Health endpoint ----
        app.MapGet("/api/v1/health", Function(pm As ProcessManager) New NodeHealthResponse With {
            .Status = "ok",
            .UptimeSeconds = CLng((DateTime.UtcNow - ProcessStartTime).TotalSeconds),
            .RunningInstanceCount = pm.GetRunningCount(),
            .ActiveInstallOperationCount = app.Services.GetRequiredService(Of InstallRunner)().ActiveCount
        })

        ' ---- Start the HTTP server ----
        app.Logger.LogInformation("GSM Node starting on port {Port}", config.Port)
        app.Run($"http://0.0.0.0:{config.Port}")
    End Sub


    Private Async Function AuthenticateRequestAsync(context As HttpContext,
                                                    [next] As Func(Of Task),
                                                    config As NodeConfiguration) As Task
        If context.Request.Path.StartsWithSegments("/api/version") Then
            Await [next]()
            Exit Function
        End If

        Dim authHeader = context.Request.Headers("Authorization").FirstOrDefault()
        Dim token As String = Nothing
        If Not String.IsNullOrEmpty(authHeader) AndAlso authHeader.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase) Then
            token = authHeader.Substring(7)
        End If

        If token <> config.AuthToken Then
            context.Response.StatusCode = 401
            Await context.Response.WriteAsJsonAsync(
                New NodeErrorResponse With {
                    .ErrorCode = "UNAUTHORISED",
                    .Message = "Invalid or missing bearer token."
                })
            Exit Function
        End If

        Await [next]()
    End Function

    Private ReadOnly ProcessStartTime As DateTime = DateTime.UtcNow

End Module


' ============================================================
'  NODE CONFIGURATION
'  Read from environment variables or nodesettings.json.
'  Validated at startup - missing required values abort launch.
' ============================================================

Public Class NodeConfiguration

    ' The bearer token the manager must present on every request.
    ' Set this to a long random string when setting up the node.
    Public Property AuthToken As String

    ' Port the HTTP server listens on.
    Public Property Port As Integer = 8765

    ' Directory where the node stores its local SQLite database,
    ' persisted instance state, and log ring buffer.
    Public Property DataDirectory As String = "data"

    ' Maximum number of log lines to keep in the ring buffer
    ' per instance. Older lines are dropped when the buffer is full.
    Public Property RingBufferCapacity As Integer = 10000

    ' How long to wait for a process to exit gracefully before
    ' force-killing it. Can be overridden per stop request.
    Public Property DefaultGracefulStopTimeoutMs As Integer = 30000

    Public Shared Function Load(config As Microsoft.Extensions.Configuration.IConfiguration) _
            As NodeConfiguration

        Dim result As New NodeConfiguration()

        ' Environment variables take priority over config file.
        ' This makes it easy to configure in Docker or systemd.
        result.AuthToken = If(Environment.GetEnvironmentVariable("GSM_NODE_TOKEN"),
                           If(config("Node:AuthToken"), ""))
        Dim parsedPort As Integer
        If Integer.TryParse(
                          If(Environment.GetEnvironmentVariable("GSM_NODE_PORT"),
                             config("Node:Port")),
                          parsedPort) Then
            result.Port = parsedPort
        Else
            result.Port = 8765
        End If
        result.DataDirectory =
                          If(Environment.GetEnvironmentVariable("GSM_NODE_DATADIR"),
                          If(config("Node:DataDirectory"), "data"))

        ' Validate required settings.
        If String.IsNullOrWhiteSpace(result.AuthToken) Then
            Throw New InvalidOperationException(
                "Node auth token is not configured. " &
                "Set the GSM_NODE_TOKEN environment variable or " &
                "Node:AuthToken in nodesettings.json. " &
                "Generate a long random string for the token.")
        End If

        Return result
    End Function

End Class


' ============================================================
'  NODE DATABASE
'  Local SQLite using Microsoft.Data.Sqlite directly.
'  No EF - the node's data needs are simple enough that raw
'  SQL is cleaner and removes a significant dependency.
'
'  What the node persists locally:
'    - Instance state: last known state, PID, stop intent flag
'    - Crash event history (for sliding window calculation)
'    - Ring buffer: recent log lines per instance
'      (stored in memory primarily; SQLite is for overflow
'       and survival across node restarts)
'
'  The node database is NOT the manager database.
'  It only stores what the node needs to operate autonomously
'  when the manager is unreachable.
' ============================================================

Public Class NodeDatabase

    Private ReadOnly _config As NodeConfiguration
    Private ReadOnly _logger As ILogger(Of NodeDatabase)
    Private ReadOnly _dbPath As String
    Private ReadOnly _connectionString As String

    Public Sub New(config As NodeConfiguration, logger As ILogger(Of NodeDatabase))
        _config = config
        _logger = logger
        Directory.CreateDirectory(config.DataDirectory)
        _dbPath = Path.Combine(config.DataDirectory, "node.db")
        _connectionString = $"Data Source={_dbPath}"
    End Sub

    Public Sub Initialise()
        _logger.LogInformation("NodeDatabase: initialising at {Path}", _dbPath)
        Using conn = OpenConnection()
            ' WAL mode for better concurrent read performance.
            ExecuteNonQuery(conn, "PRAGMA journal_mode = WAL;")
            ExecuteNonQuery(conn, "PRAGMA foreign_keys = ON;")

            ' ---- Instance state table ----
            ' One row per instance the node has ever been asked to manage.
            ' The StopIntentPending flag is critical: it distinguishes a
            ' crash (process died unexpectedly) from a clean stop (we asked
            ' it to stop). Must survive node restarts.
            ExecuteNonQuery(conn, "
                CREATE TABLE IF NOT EXISTS InstanceState (
                    InstanceId          TEXT PRIMARY KEY NOT NULL,
                    DisplayName         TEXT NOT NULL DEFAULT '',
                    GameId              TEXT NOT NULL DEFAULT '',
                    InstallationId      TEXT NOT NULL DEFAULT '',
                    State               TEXT NOT NULL DEFAULT 'Stopped',
                    Pid                 INTEGER,
                    StopIntentPending   INTEGER NOT NULL DEFAULT 0,
                    StartedAt           TEXT,
                    LastStateChangeAt   TEXT NOT NULL,
                    CrashRestartJson    TEXT NOT NULL DEFAULT '{}',
                    LastStartParamsJson TEXT NOT NULL DEFAULT '{}'
                );")

            ' ---- Crash event table ----
            ' Every crash and restart decision is recorded here.
            ' Used for the sliding window crash loop detection.
            ' Manager reads this via GET /instances/{id} for display.
            ExecuteNonQuery(conn, "
                CREATE TABLE IF NOT EXISTS CrashEvents (
                    CrashEventId        TEXT PRIMARY KEY NOT NULL,
                    InstanceId          TEXT NOT NULL,
                    OccurredAt          TEXT NOT NULL,
                    ExitCode            INTEGER NOT NULL,
                    StopIntentWasSet    INTEGER NOT NULL DEFAULT 0,
                    Decision            TEXT NOT NULL,
                    DecisionReason      TEXT NOT NULL,
                    AttemptNumber       INTEGER NOT NULL DEFAULT 0,
                    BackoffAppliedMs    INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY (InstanceId)
                        REFERENCES InstanceState (InstanceId) ON DELETE CASCADE
                );")

            ExecuteNonQuery(conn,
                "CREATE INDEX IF NOT EXISTS idx_crashevents_instanceid_time
                 ON CrashEvents (InstanceId, OccurredAt DESC);")

            ' ---- Ring buffer table ----
            ' Stores recent log lines per instance.
            ' LineIndex is monotonically increasing per instance.
            ' Used for hot-reload checkpoint/replay and for the
            ' GET /instances/{id}/logs endpoint.
            ' Rows older than the capacity cap are pruned on insert.
            ExecuteNonQuery(conn, "
                CREATE TABLE IF NOT EXISTS RingBuffer (
                    RowId       INTEGER PRIMARY KEY AUTOINCREMENT,
                    InstanceId  TEXT NOT NULL,
                    LineIndex   INTEGER NOT NULL,
                    SourceId    TEXT NOT NULL,
                    Timestamp   TEXT NOT NULL,
                    Content     TEXT NOT NULL
                );")

            ExecuteNonQuery(conn,
                "CREATE INDEX IF NOT EXISTS idx_ringbuffer_instance_line
                 ON RingBuffer (InstanceId, LineIndex DESC);")

            ' ---- Install operation state ----
            ' One row per installation, tracks active install/update.
            ExecuteNonQuery(conn, "
                CREATE TABLE IF NOT EXISTS InstallState (
                    InstallationId      TEXT PRIMARY KEY NOT NULL,
                    State               TEXT NOT NULL DEFAULT 'Idle',
                    CurrentStepIndex    INTEGER NOT NULL DEFAULT 0,
                    TotalSteps          INTEGER NOT NULL DEFAULT 0,
                    CurrentStepDesc     TEXT NOT NULL DEFAULT '',
                    StartedAt           TEXT,
                    CompletedAt         TEXT,
                    ErrorMessage        TEXT NOT NULL DEFAULT '',
                    Pid                 INTEGER,
                    PendingPromptJson   TEXT NOT NULL DEFAULT ''
                );")
        End Using

        _logger.LogInformation("NodeDatabase: ready")
    End Sub

    ' ---- Instance state operations ----

    Public Sub UpsertInstanceState(state As PersistedInstanceState)
        Using conn = OpenConnection()
            ExecuteNonQuery(conn, "
                INSERT INTO InstanceState
                    (InstanceId, DisplayName, GameId, InstallationId,
                     State, Pid, StopIntentPending, StartedAt,
                     LastStateChangeAt, CrashRestartJson, LastStartParamsJson)
                VALUES
                    (@id, @name, @gameId, @installId,
                     @state, @pid, @stopIntent, @startedAt,
                     @stateChangeAt, @crashRestart, @startParams)
                ON CONFLICT(InstanceId) DO UPDATE SET
                    DisplayName         = excluded.DisplayName,
                    GameId              = excluded.GameId,
                    InstallationId      = excluded.InstallationId,
                    State               = excluded.State,
                    Pid                 = excluded.Pid,
                    StopIntentPending   = excluded.StopIntentPending,
                    StartedAt           = excluded.StartedAt,
                    LastStateChangeAt   = excluded.LastStateChangeAt,
                    CrashRestartJson    = excluded.CrashRestartJson,
                    LastStartParamsJson = excluded.LastStartParamsJson;",
                ("@id",           state.InstanceId),
                ("@name",         state.DisplayName),
                ("@gameId",       state.GameId),
                ("@installId",    state.InstallationId),
                ("@state",        state.State.ToString()),
                ("@pid",          If(state.Pid.HasValue, CObj(state.Pid.Value), DBNull.Value)),
                ("@stopIntent",   If(state.StopIntentPending, 1, 0)),
                ("@startedAt",    If(state.StartedAt.HasValue,
                                     CObj(state.StartedAt.Value.ToString("o")), DBNull.Value)),
                ("@stateChangeAt", state.LastStateChangeAt.ToString("o")),
                ("@crashRestart", state.CrashRestartJson),
                ("@startParams",  state.LastStartParamsJson))
        End Using
    End Sub

    Public Function GetAllInstanceStates() As List(Of PersistedInstanceState)
        Using conn = OpenConnection()
            Return QueryAll(conn,
                "SELECT * FROM InstanceState;",
                AddressOf MapInstanceState)
        End Using
    End Function

    Public Function GetInstanceState(instanceId As String) As PersistedInstanceState
        Using conn = OpenConnection()
            Return QueryFirst(conn,
                "SELECT * FROM InstanceState WHERE InstanceId = @id;",
                AddressOf MapInstanceState,
                ("@id", instanceId))
        End Using
    End Function

    ' Update just the stop intent flag - called frequently and must be atomic.
    Public Sub SetStopIntent(instanceId As String, pending As Boolean)
        Using conn = OpenConnection()
            ExecuteNonQuery(conn,
                "UPDATE InstanceState SET StopIntentPending = @v WHERE InstanceId = @id;",
                ("@v", If(pending, 1, 0)), ("@id", instanceId))
        End Using
    End Sub

    ' ---- Crash event operations ----

    Public Sub InsertCrashEvent(ev As CrashEventRecord)
        Using conn = OpenConnection()
            ExecuteNonQuery(conn, "
                INSERT INTO CrashEvents
                    (CrashEventId, InstanceId, OccurredAt, ExitCode,
                     StopIntentWasSet, Decision, DecisionReason,
                     AttemptNumber, BackoffAppliedMs)
                VALUES
                    (@id, @inst, @at, @code, @intent,
                     @decision, @reason, @attempt, @backoff);",
                ("@id",       ev.CrashEventId),
                ("@inst",     ev.InstanceId),
                ("@at",       ev.OccurredAt.ToString("o")),
                ("@code",     ev.ExitCode),
                ("@intent",   If(ev.StopIntentWasSet, 1, 0)),
                ("@decision", ev.Decision),
                ("@reason",   ev.DecisionReason),
                ("@attempt",  ev.AttemptNumber),
                ("@backoff",  ev.BackoffAppliedMs))
        End Using
    End Sub

    ' Returns crashes within the sliding window for loop detection.
    Public Function GetRecentCrashes(instanceId As String,
                                     windowStart As DateTime) As List(Of CrashEventRecord)
        Using conn = OpenConnection()
            Return QueryAll(conn, "
                SELECT * FROM CrashEvents
                WHERE InstanceId = @id AND OccurredAt >= @since
                ORDER BY OccurredAt DESC;",
                AddressOf MapCrashEvent,
                ("@id", instanceId),
                ("@since", windowStart.ToString("o")))
        End Using
    End Function

    ' ---- Ring buffer operations ----

    Public Sub AppendLogLine(instanceId As String,
                             lineIndex As Long,
                             sourceId As String,
                             timestamp As DateTime,
                             content As String,
                             capacity As Integer)
        Using conn = OpenConnection()
            ' Insert the new line.
            ExecuteNonQuery(conn, "
                INSERT INTO RingBuffer (InstanceId, LineIndex, SourceId, Timestamp, Content)
                VALUES (@inst, @idx, @src, @ts, @content);",
                ("@inst",    instanceId),
                ("@idx",     lineIndex),
                ("@src",     sourceId),
                ("@ts",      timestamp.ToString("o")),
                ("@content", content))

            ' Prune oldest lines if over capacity.
            ' We keep the most recent {capacity} lines per instance.
            ExecuteNonQuery(conn, "
                DELETE FROM RingBuffer
                WHERE InstanceId = @inst
                  AND RowId NOT IN (
                      SELECT RowId FROM RingBuffer
                      WHERE InstanceId = @inst
                      ORDER BY LineIndex DESC
                      LIMIT @cap
                  );",
                ("@inst", instanceId),
                ("@cap",  capacity))
        End Using
    End Sub

    Public Function GetRecentLines(instanceId As String,
                                   count As Integer,
                                   sourceId As String) As List(Of BufferedLogLineRecord)
        Using conn = OpenConnection()
            Dim sourceFilter = If(String.IsNullOrEmpty(sourceId),
                                  "", " AND SourceId = @src")
            Dim rows = QueryAll(conn, $"
                SELECT LineIndex, SourceId, Timestamp, Content
                FROM RingBuffer
                WHERE InstanceId = @inst{sourceFilter}
                ORDER BY LineIndex DESC
                LIMIT @count;",
                AddressOf MapLogLine,
                ("@inst", instanceId),
                ("@count", count),
                ("@src", If(sourceId, "")))
            rows.Reverse()  ' Return in chronological order
            Return rows
        End Using
    End Function

    Public Function GetLinesFromIndex(instanceId As String,
                                      fromIndex As Long) As List(Of BufferedLogLineRecord)
        Using conn = OpenConnection()
            Return QueryAll(conn, "
                SELECT LineIndex, SourceId, Timestamp, Content
                FROM RingBuffer
                WHERE InstanceId = @inst AND LineIndex >= @from
                ORDER BY LineIndex ASC;",
                AddressOf MapLogLine,
                ("@inst", instanceId),
                ("@from", fromIndex))
        End Using
    End Function

    ' ---- Install state operations ----

    Public Sub UpsertInstallState(state As InstallOperationState)
        Using conn = OpenConnection()
            ExecuteNonQuery(conn, "
                INSERT INTO InstallState
                    (InstallationId, State, CurrentStepIndex, TotalSteps,
                     CurrentStepDesc, StartedAt, CompletedAt,
                     ErrorMessage, Pid, PendingPromptJson)
                VALUES
                    (@id, @state, @stepIdx, @totalSteps,
                     @stepDesc, @startedAt, @completedAt,
                     @error, @pid, @prompt)
                ON CONFLICT(InstallationId) DO UPDATE SET
                    State            = excluded.State,
                    CurrentStepIndex = excluded.CurrentStepIndex,
                    TotalSteps       = excluded.TotalSteps,
                    CurrentStepDesc  = excluded.CurrentStepDesc,
                    StartedAt        = excluded.StartedAt,
                    CompletedAt      = excluded.CompletedAt,
                    ErrorMessage     = excluded.ErrorMessage,
                    Pid              = excluded.Pid,
                    PendingPromptJson = excluded.PendingPromptJson;",
                ("@id",         state.InstallationId),
                ("@state",      state.State),
                ("@stepIdx",    state.CurrentStepIndex),
                ("@totalSteps", state.TotalSteps),
                ("@stepDesc",   state.CurrentStepDesc),
                ("@startedAt",  If(state.StartedAt.HasValue,
                                    CObj(state.StartedAt.Value.ToString("o")), DBNull.Value)),
                ("@completedAt", If(state.CompletedAt.HasValue,
                                    CObj(state.CompletedAt.Value.ToString("o")), DBNull.Value)),
                ("@error",      state.ErrorMessage),
                ("@pid",        If(state.Pid.HasValue, CObj(state.Pid.Value), DBNull.Value)),
                ("@prompt",     state.PendingPromptJson))
        End Using
    End Sub

    Public Function GetInstallState(installationId As String) As InstallOperationState
        Using conn = OpenConnection()
            Return QueryFirst(conn,
                "SELECT * FROM InstallState WHERE InstallationId = @id;",
                AddressOf MapInstallState,
                ("@id", installationId))
        End Using
    End Function


    ' ============================================================
    '  PRIVATE HELPERS
    '  Thin wrappers around Microsoft.Data.Sqlite that keep the
    '  query code above readable without a full ORM.
    ' ============================================================

    Private Function OpenConnection() As Microsoft.Data.Sqlite.SqliteConnection
        Dim conn As New Microsoft.Data.Sqlite.SqliteConnection(_connectionString)
        conn.Open()
        Return conn
    End Function

    Private Sub ExecuteNonQuery(conn As Microsoft.Data.Sqlite.SqliteConnection,
                                 sql As String,
                                 ParamArray parameters As (Name As String, Value As Object)())
        Using cmd = conn.CreateCommand()
            cmd.CommandText = sql
            For Each p In parameters
                cmd.Parameters.AddWithValue(p.Name, p.Value)
            Next
            cmd.ExecuteNonQuery()
        End Using
    End Sub

    Private Function QueryAll(Of T)(
            conn As Microsoft.Data.Sqlite.SqliteConnection,
            sql As String,
            mapper As Func(Of Microsoft.Data.Sqlite.SqliteDataReader, T),
            ParamArray parameters As (Name As String, Value As Object)()) As List(Of T)
        Using cmd = conn.CreateCommand()
            cmd.CommandText = sql
            For Each p In parameters
                If Not String.IsNullOrEmpty(p.Name) Then
                    cmd.Parameters.AddWithValue(p.Name, p.Value)
                End If
            Next
            Using reader = cmd.ExecuteReader()
                Dim results As New List(Of T)
                Do While reader.Read()
                    results.Add(mapper(reader))
                Loop
                Return results
            End Using
        End Using
    End Function

    Private Function QueryFirst(Of T As Class)(
            conn As Microsoft.Data.Sqlite.SqliteConnection,
            sql As String,
            mapper As Func(Of Microsoft.Data.Sqlite.SqliteDataReader, T),
            ParamArray parameters As (Name As String, Value As Object)()) As T
        Using cmd = conn.CreateCommand()
            cmd.CommandText = sql
            For Each p In parameters
                cmd.Parameters.AddWithValue(p.Name, p.Value)
            Next
            Using reader = cmd.ExecuteReader()
                If reader.Read() Then Return mapper(reader)
                Return Nothing
            End Using
        End Using
    End Function

    ' ---- Row mappers ----

    Private Function MapInstanceState(
            r As Microsoft.Data.Sqlite.SqliteDataReader) As PersistedInstanceState
        Return New PersistedInstanceState With {
            .InstanceId = r.GetString(r.GetOrdinal("InstanceId")),
            .DisplayName = r.GetString(r.GetOrdinal("DisplayName")),
            .GameId = r.GetString(r.GetOrdinal("GameId")),
            .InstallationId = r.GetString(r.GetOrdinal("InstallationId")),
            .State = [Enum].Parse(GetType(GSM.Plugin.InstanceState),
                                   r.GetString(r.GetOrdinal("State"))),
            .Pid = If(r.IsDBNull(r.GetOrdinal("Pid")), CType(Nothing, Integer?),
                      r.GetInt32(r.GetOrdinal("Pid"))),
            .StopIntentPending = r.GetInt32(r.GetOrdinal("StopIntentPending")) = 1,
            .StartedAt = If(r.IsDBNull(r.GetOrdinal("StartedAt")), CType(Nothing, DateTime?),
                            DateTime.Parse(r.GetString(r.GetOrdinal("StartedAt")))),
            .LastStateChangeAt = DateTime.Parse(r.GetString(r.GetOrdinal("LastStateChangeAt"))),
            .CrashRestartJson = r.GetString(r.GetOrdinal("CrashRestartJson")),
            .LastStartParamsJson = r.GetString(r.GetOrdinal("LastStartParamsJson"))
        }
    End Function

    Private Function MapCrashEvent(
            r As Microsoft.Data.Sqlite.SqliteDataReader) As CrashEventRecord
        Return New CrashEventRecord With {
            .CrashEventId = r.GetString(r.GetOrdinal("CrashEventId")),
            .InstanceId = r.GetString(r.GetOrdinal("InstanceId")),
            .OccurredAt = DateTime.Parse(r.GetString(r.GetOrdinal("OccurredAt"))),
            .ExitCode = r.GetInt32(r.GetOrdinal("ExitCode")),
            .StopIntentWasSet = r.GetInt32(r.GetOrdinal("StopIntentWasSet")) = 1,
            .Decision = r.GetString(r.GetOrdinal("Decision")),
            .DecisionReason = r.GetString(r.GetOrdinal("DecisionReason")),
            .AttemptNumber = r.GetInt32(r.GetOrdinal("AttemptNumber")),
            .BackoffAppliedMs = r.GetInt32(r.GetOrdinal("BackoffAppliedMs"))
        }
    End Function

    Private Function MapLogLine(
            r As Microsoft.Data.Sqlite.SqliteDataReader) As BufferedLogLineRecord
        Return New BufferedLogLineRecord With {
            .LineIndex = r.GetInt64(r.GetOrdinal("LineIndex")),
            .SourceId = r.GetString(r.GetOrdinal("SourceId")),
            .Timestamp = DateTime.Parse(r.GetString(r.GetOrdinal("Timestamp"))),
            .Content = r.GetString(r.GetOrdinal("Content"))
        }
    End Function

    Private Function MapInstallState(
            r As Microsoft.Data.Sqlite.SqliteDataReader) As InstallOperationState
        Return New InstallOperationState With {
            .InstallationId = r.GetString(r.GetOrdinal("InstallationId")),
            .State = r.GetString(r.GetOrdinal("State")),
            .CurrentStepIndex = r.GetInt32(r.GetOrdinal("CurrentStepIndex")),
            .TotalSteps = r.GetInt32(r.GetOrdinal("TotalSteps")),
            .CurrentStepDesc = r.GetString(r.GetOrdinal("CurrentStepDesc")),
            .StartedAt = If(r.IsDBNull(r.GetOrdinal("StartedAt")), CType(Nothing, DateTime?),
                            DateTime.Parse(r.GetString(r.GetOrdinal("StartedAt")))),
            .CompletedAt = If(r.IsDBNull(r.GetOrdinal("CompletedAt")), CType(Nothing, DateTime?),
                              DateTime.Parse(r.GetString(r.GetOrdinal("CompletedAt")))),
            .ErrorMessage = r.GetString(r.GetOrdinal("ErrorMessage")),
            .Pid = If(r.IsDBNull(r.GetOrdinal("Pid")), CType(Nothing, Integer?),
                      r.GetInt32(r.GetOrdinal("Pid"))),
            .PendingPromptJson = r.GetString(r.GetOrdinal("PendingPromptJson"))
        }
    End Function

End Class


' ============================================================
'  LOCAL DATA RECORDS
'  Plain classes used only within the node.
'  Not shared with the manager - the manager sees these
'  through the API response DTOs in NodeApiContract.vb.
' ============================================================

Public Class PersistedInstanceState
    Public Property InstanceId As String
    Public Property DisplayName As String
    Public Property GameId As String
    Public Property InstallationId As String
    Public Property State As GSM.Plugin.InstanceState
    Public Property Pid As Integer?
    Public Property StopIntentPending As Boolean
    Public Property StartedAt As DateTime?
    Public Property LastStateChangeAt As DateTime
    Public Property CrashRestartJson As String
    Public Property LastStartParamsJson As String
End Class

Public Class CrashEventRecord
    Public Property CrashEventId As String
    Public Property InstanceId As String
    Public Property OccurredAt As DateTime
    Public Property ExitCode As Integer
    Public Property StopIntentWasSet As Boolean
    Public Property Decision As String
    Public Property DecisionReason As String
    Public Property AttemptNumber As Integer
    Public Property BackoffAppliedMs As Integer
End Class

Public Class BufferedLogLineRecord
    Public Property LineIndex As Long
    Public Property SourceId As String
    Public Property Timestamp As DateTime
    Public Property Content As String
End Class

Public Class InstallOperationState
    Public Property InstallationId As String
    Public Property State As String
    Public Property CurrentStepIndex As Integer
    Public Property TotalSteps As Integer
    Public Property CurrentStepDesc As String
    Public Property StartedAt As DateTime?
    Public Property CompletedAt As DateTime?
    Public Property ErrorMessage As String
    Public Property Pid As Integer?
    Public Property PendingPromptJson As String
End Class
