-- ============================================================
--  GSM Manager Database Schema
--  SQLite · managed by EF Core migrations
--
--  Scope: This is the MANAGER-side database only.
--  Nodes maintain their own local SQLite for:
--    - Persisted instance state (PID, stop intent flag)
--    - Crash event history
--    - Log ring buffer
--  Those schemas are defined separately in the node project.
--
--  All primary keys are TEXT GUIDs generated by the application.
--  All timestamps are UTC ISO 8601 strings.
--  Boolean columns are INTEGER (0/1) per SQLite convention.
--  Sensitive fields (passwords, keys) are stored as BLOB
--  containing DPAPI-encrypted bytes. Never stored as plaintext.
-- ============================================================

PRAGMA journal_mode = WAL;      -- Better concurrent read performance
PRAGMA foreign_keys = ON;       -- Enforce FK constraints
PRAGMA synchronous = NORMAL;    -- Safe with WAL, faster than FULL


-- ============================================================
--  NODES
--  One row per managed machine. A node runs the GSM node
--  service and exposes the REST API defined in NodeApiContract.
-- ============================================================

CREATE TABLE IF NOT EXISTS Nodes (
    NodeId          TEXT PRIMARY KEY NOT NULL,  -- GUID
    DisplayName     TEXT NOT NULL,
    Hostname        TEXT NOT NULL,              -- DNS name or IP
    Port            INTEGER NOT NULL DEFAULT 8765,
    AuthToken       BLOB NOT NULL,              -- DPAPI-encrypted bearer token
    Os              TEXT NOT NULL,              -- "Windows" or "Linux"
    IsEnabled       INTEGER NOT NULL DEFAULT 1,
    Notes           TEXT NOT NULL DEFAULT '',
    AddedAt         TEXT NOT NULL,
    LastSeenAt      TEXT,                       -- NULL = never connected
    LastKnownVersion TEXT,                      -- Node API version string
    -- Cached system info (refreshed on connect)
    CachedHostname  TEXT,
    CachedCpuName   TEXT,
    CachedTotalMemoryMb INTEGER
);

CREATE INDEX IF NOT EXISTS idx_nodes_hostname ON Nodes (Hostname);


-- ============================================================
--  STEAM CREDENTIALS
--  One row per Steam account. Passwords encrypted via DPAPI.
--  Referenced by installations that require SteamCMD login.
--  Never stored on nodes - transmitted transiently at install time.
-- ============================================================

CREATE TABLE IF NOT EXISTS SteamCredentials (
    CredentialId        TEXT PRIMARY KEY NOT NULL,  -- GUID
    DisplayName         TEXT NOT NULL,
    Username            TEXT NOT NULL,
    EncryptedPassword   BLOB,               -- NULL if IsAnonymous = 1
    IsAnonymous         INTEGER NOT NULL DEFAULT 0,
    GameId              TEXT NOT NULL DEFAULT '', -- Empty = usable for any game
    Notes               TEXT NOT NULL DEFAULT '',
    CreatedAt           TEXT NOT NULL,
    LastUsedAt          TEXT
);

CREATE INDEX IF NOT EXISTS idx_steamcreds_gameid ON SteamCredentials (GameId);


-- ============================================================
--  REALM CREDENTIALS
--  One row per game realm. CustomerKey and ProviderKey encrypted.
--  Referenced by installations and instances.
--  A single credential covers all instances on a realm.
-- ============================================================

CREATE TABLE IF NOT EXISTS RealmCredentials (
    CredentialId        TEXT PRIMARY KEY NOT NULL,  -- GUID
    DisplayName         TEXT NOT NULL,
    GameId              TEXT NOT NULL,
    EncryptedCustomerKey BLOB NOT NULL,     -- DPAPI-encrypted
    EncryptedProviderKey BLOB NOT NULL,     -- DPAPI-encrypted
    Notes               TEXT NOT NULL DEFAULT '',
    CreatedAt           TEXT NOT NULL,
    LastUsedAt          TEXT
);

CREATE INDEX IF NOT EXISTS idx_realmcreds_gameid ON RealmCredentials (GameId);


-- ============================================================
--  INSTALLATIONS
--  One row per set of game server files on a node.
--  Multiple instances can share one installation (Last Oasis).
--  Each installation belongs to exactly one node.
-- ============================================================

CREATE TABLE IF NOT EXISTS Installations (
    InstallationId      TEXT PRIMARY KEY NOT NULL,  -- GUID
    DisplayName         TEXT NOT NULL,
    GameId              TEXT NOT NULL,
    NodeId              TEXT NOT NULL REFERENCES Nodes (NodeId) ON DELETE RESTRICT,
    InstallPath         TEXT NOT NULL,              -- Absolute path on the node
    InstallMethod       TEXT NOT NULL,              -- "SteamCMD" or "DirectDownload"
    RealmCredentialId   TEXT REFERENCES RealmCredentials (CredentialId) ON DELETE SET NULL,
    SteamCredentialId   TEXT REFERENCES SteamCredentials (CredentialId) ON DELETE SET NULL,
    -- Plugin config blob (game-specific fields as JSON)
    PluginConfig        TEXT NOT NULL DEFAULT '{}',
    InstalledVersion    TEXT NOT NULL DEFAULT '',
    LastUpdatedAt       TEXT,
    LastValidatedAt     TEXT,
    IsEnabled           INTEGER NOT NULL DEFAULT 1,
    Notes               TEXT NOT NULL DEFAULT '',
    CreatedAt           TEXT NOT NULL,
    -- Installation lock state persisted to survive manager restarts
    LockState           TEXT NOT NULL DEFAULT 'None', -- "None", "ReadLocked", "WriteLocked"
    WriteLockHeldSince  TEXT,                         -- NULL if not write-locked
    WriteLockReason     TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_installations_nodeid  ON Installations (NodeId);
CREATE INDEX IF NOT EXISTS idx_installations_gameid  ON Installations (GameId);


-- ============================================================
--  INSTANCES
--  One row per running server instance.
--  Each instance belongs to one installation and runs on
--  the same node as that installation.
-- ============================================================

CREATE TABLE IF NOT EXISTS Instances (
    InstanceId          TEXT PRIMARY KEY NOT NULL,  -- GUID
    DisplayName         TEXT NOT NULL,
    GameId              TEXT NOT NULL,
    InstallationId      TEXT NOT NULL REFERENCES Installations (InstallationId) ON DELETE RESTRICT,
    -- Optional credential override: uses installation's credential if NULL
    RealmCredentialId   TEXT REFERENCES RealmCredentials (CredentialId) ON DELETE SET NULL,
    -- Optional exe override: uses plugin's resolved path if empty
    ExeOverride         TEXT NOT NULL DEFAULT '',
    -- Plugin config blob (game-specific fields as JSON)
    -- Manager merges realm credential keys into this before sending to node
    PluginConfig        TEXT NOT NULL DEFAULT '{}',
    -- Crash restart policy (JSON-serialised CrashRestartPolicy)
    CrashRestartPolicy  TEXT NOT NULL DEFAULT '{}',
    IsEnabled           INTEGER NOT NULL DEFAULT 1,
    Notes               TEXT NOT NULL DEFAULT '',
    CreatedAt           TEXT NOT NULL,
    SortOrder           INTEGER NOT NULL DEFAULT 0, -- Display order in UI
    -- Last known state (cached from node - source of truth is the node)
    LastKnownState      TEXT NOT NULL DEFAULT 'Stopped',
    LastKnownRconState  TEXT NOT NULL DEFAULT 'NotAvailable',
    LastKnownPlayerCount INTEGER NOT NULL DEFAULT 0,
    LastStateReportAt   TEXT
);

CREATE INDEX IF NOT EXISTS idx_instances_installationid ON Instances (InstallationId);
CREATE INDEX IF NOT EXISTS idx_instances_gameid         ON Instances (GameId);


-- ============================================================
--  AUTOMATION RULES
--  One row per rule. Trigger, conditions, and action are stored
--  as JSON blobs using the types defined in IAutomationRule.vb.
--  The automation engine deserialises these at runtime.
-- ============================================================

CREATE TABLE IF NOT EXISTS AutomationRules (
    RuleId              TEXT PRIMARY KEY NOT NULL,  -- GUID
    DisplayName         TEXT NOT NULL,
    IsEnabled           INTEGER NOT NULL DEFAULT 1,
    Scope               TEXT NOT NULL,  -- "Instance", "Installation", "Global"
    -- ID of the instance or installation this rule targets.
    -- Empty if Scope = "Global".
    TargetId            TEXT NOT NULL DEFAULT '',
    -- JSON-serialised ITrigger
    TriggerJson         TEXT NOT NULL,
    -- JSON array of serialised ICondition
    ConditionsJson      TEXT NOT NULL DEFAULT '[]',
    ConditionMode       TEXT NOT NULL DEFAULT 'All', -- "All" or "Any"
    -- JSON-serialised IAction (may be a SequenceAction)
    ActionJson          TEXT NOT NULL,
    OnConcurrentFire    TEXT NOT NULL DEFAULT 'Skip', -- "Skip", "Queue", "Cancel"
    CreatedAt           TEXT NOT NULL,
    LastModifiedAt      TEXT NOT NULL,
    LastFiredAt         TEXT,
    FireCount           INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_rules_scope    ON AutomationRules (Scope);
CREATE INDEX IF NOT EXISTS idx_rules_targetid ON AutomationRules (TargetId);
CREATE INDEX IF NOT EXISTS idx_rules_enabled  ON AutomationRules (IsEnabled);


-- ============================================================
--  RULE EXECUTION HISTORY
--  Capped at 100 entries per rule (enforced by application).
--  Provides audit trail for every rule execution including
--  per-condition results and the final action outcome.
-- ============================================================

CREATE TABLE IF NOT EXISTS RuleExecutionHistory (
    ExecutionId         TEXT PRIMARY KEY NOT NULL,  -- GUID
    RuleId              TEXT NOT NULL REFERENCES AutomationRules (RuleId) ON DELETE CASCADE,
    ExecutedAt          TEXT NOT NULL,
    TriggerSource       TEXT NOT NULL,              -- Human label of what fired it
    -- JSON array of per-condition {label, passed, reason} objects
    ConditionResultsJson TEXT NOT NULL DEFAULT '[]',
    ActionSuccess       INTEGER NOT NULL DEFAULT 0,
    ActionMessage       TEXT NOT NULL DEFAULT '',
    -- JSON array of step-by-step action log entries
    ActionDetailsJson   TEXT NOT NULL DEFAULT '[]',
    DurationMs          INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_rulehistory_ruleid     ON RuleExecutionHistory (RuleId);
CREATE INDEX IF NOT EXISTS idx_rulehistory_executedat ON RuleExecutionHistory (ExecutedAt DESC);


-- ============================================================
--  NOTIFICATION PLUGIN CONFIGS
--  One row per notification plugin (Discord, Telegram, etc).
--  Config blob contains plugin-specific settings (tokens,
--  channel IDs, etc) - sensitive values DPAPI-encrypted
--  within the JSON by the plugin itself.
-- ============================================================

CREATE TABLE IF NOT EXISTS NotificationPluginConfigs (
    PluginConfigId  TEXT PRIMARY KEY NOT NULL,  -- GUID
    PluginId        TEXT NOT NULL UNIQUE,       -- e.g. "discord"
    DisplayName     TEXT NOT NULL,
    IsEnabled       INTEGER NOT NULL DEFAULT 1,
    -- Plugin-specific config as JSON. Sensitive fields within
    -- this blob are encrypted by the plugin before storage.
    ConfigJson      TEXT NOT NULL DEFAULT '{}',
    CreatedAt       TEXT NOT NULL,
    LastModifiedAt  TEXT NOT NULL
);


-- ============================================================
--  NOTIFICATION SUBSCRIPTIONS
--  Links a set of event types to a named route for a specific
--  instance or installation. The notification plugin resolves
--  the route name to a platform destination (channel ID etc).
-- ============================================================

CREATE TABLE IF NOT EXISTS NotificationSubscriptions (
    SubscriptionId  TEXT PRIMARY KEY NOT NULL,  -- GUID
    PluginId        TEXT NOT NULL,              -- Which notification plugin
    Scope           TEXT NOT NULL,              -- "Instance" or "Installation"
    TargetId        TEXT NOT NULL,              -- InstanceId or InstallationId
    -- JSON array of NotificationEventType strings
    EventTypesJson  TEXT NOT NULL DEFAULT '[]',
    RouteName       TEXT NOT NULL DEFAULT '',   -- Plugin-defined route e.g. "admin"
    IsEnabled       INTEGER NOT NULL DEFAULT 1,
    CreatedAt       TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notif_subs_targetid ON NotificationSubscriptions (TargetId);
CREATE INDEX IF NOT EXISTS idx_notif_subs_pluginid ON NotificationSubscriptions (PluginId);


-- ============================================================
--  MANAGER EVENT LOG
--  Persistent audit log of significant manager-side events.
--  Separate from node-side crash history and instance state events.
--  Used for the manager's own activity log in the UI.
--  Capped at 10,000 rows (enforced by application via trigger).
-- ============================================================

CREATE TABLE IF NOT EXISTS ManagerEventLog (
    EventId         TEXT PRIMARY KEY NOT NULL,  -- GUID
    OccurredAt      TEXT NOT NULL,
    Severity        TEXT NOT NULL,  -- "Info", "Warning", "Error"
    Category        TEXT NOT NULL,  -- "Plugin", "Node", "Instance", "Install", "Rule", "System"
    TargetId        TEXT,           -- InstanceId, NodeId, RuleId etc - contextual
    TargetName      TEXT,           -- Human name of the target at time of event
    Message         TEXT NOT NULL,
    Details         TEXT NOT NULL DEFAULT ''  -- Extended info, stack traces etc
);

CREATE INDEX IF NOT EXISTS idx_eventlog_occurredat ON ManagerEventLog (OccurredAt DESC);
CREATE INDEX IF NOT EXISTS idx_eventlog_category   ON ManagerEventLog (Category);
CREATE INDEX IF NOT EXISTS idx_eventlog_targetid   ON ManagerEventLog (TargetId);

-- Auto-prune trigger: keep the log capped at 10,000 rows.
CREATE TRIGGER IF NOT EXISTS trg_eventlog_prune
AFTER INSERT ON ManagerEventLog
WHEN (SELECT COUNT(*) FROM ManagerEventLog) > 10000
BEGIN
    DELETE FROM ManagerEventLog
    WHERE EventId IN (
        SELECT EventId FROM ManagerEventLog
        ORDER BY OccurredAt ASC
        LIMIT (SELECT COUNT(*) - 10000 FROM ManagerEventLog)
    );
END;


-- ============================================================
--  MANAGER SETTINGS
--  Simple key-value store for global manager configuration.
--  Used for settings that don't belong to a specific entity.
-- ============================================================

CREATE TABLE IF NOT EXISTS Settings (
    Key     TEXT PRIMARY KEY NOT NULL,
    Value   TEXT NOT NULL,
    UpdatedAt TEXT NOT NULL
);

-- Seed default settings
INSERT OR IGNORE INTO Settings (Key, Value, UpdatedAt) VALUES
    ('PluginsDirectory',        'plugins',  datetime('now')),
    ('MetricsPollIntervalSec',  '30',       datetime('now')),
    ('VersionPollIntervalMin',  '15',       datetime('now')),
    ('LogBufferLineCap',        '10000',    datetime('now')),
    ('RuleHistoryCapPerRule',   '100',      datetime('now')),
    ('NodeConnectTimeoutSec',   '10',       datetime('now')),
    ('NodeRequestTimeoutSec',   '30',       datetime('now'));
