Imports System.Drawing
Imports System.Threading
Imports System.Threading.Tasks
Imports System.Windows.Forms
Imports GSM.Core
Imports GSM.Data
Imports GSM.Plugin

' ============================================================
'  NewInstallationForm
'
'  A three-step wizard:
'    Step 1: Choose game (loaded from PluginRegistry)
'             and set a display name
'    Step 2: Plugin-driven installation config
'             (SchemaFormBuilder renders the fields)
'    Step 3: Review and confirm
'
'  On OK the form creates the InstallationEntity in the DB
'  via InstallationManager, then optionally launches the
'  install operation immediately.
'
'  The SchemaFormBuilder in Step 2 means this form works for
'  any game without any game-specific code here.
' ============================================================

Public Class NewInstallationForm
    Inherits Form

    ' ---- Dependencies ----
    Private ReadOnly _nodeId As String
    Private ReadOnly _pluginRegistry As PluginRegistry
    Private ReadOnly _installationManager As InstallationManager
    Private ReadOnly _credentialService As CredentialService

    ' ---- Wizard state ----
    Private _currentStep As Integer = 1
    Private Const TotalSteps As Integer = 3
    Private _selectedPlugin As IGamePlugin
    Private _schemaBuilder As SchemaFormBuilder

    ' ---- Controls ----
    ' Step panels
    Private _pnlStep1 As Panel
    Private _pnlStep2 As Panel
    Private _pnlStep3 As Panel

    ' Step 1 controls
    Private _lstGames As ListBox
    Private _txtDisplayName As TextBox
    Private _txtInstallPath As TextBox
    Private _btnBrowsePath As Button
    Private _cboInstallMethod As ComboBox

    ' Step 2 controls (plugin config, generated by SchemaFormBuilder)
    Private _schemaPanel As Panel

    ' Step 3 controls (review)
    Private _txtReview As RichTextBox
    Private _chkInstallNow As CheckBox

    ' Navigation
    Private _btnBack As Button
    Private _btnNext As Button
    Private _btnCancel As Button
    Private _lblStepIndicator As Label

    ' ---- Result ----
    Public Property CreatedInstallationId As String

    Public Sub New(nodeId As String,
                   pluginRegistry As PluginRegistry,
                   installationManager As InstallationManager,
                   credentialService As CredentialService)
        _nodeId = nodeId
        _pluginRegistry = pluginRegistry
        _installationManager = installationManager
        _credentialService = credentialService

        Text = "New Installation"
        Size = New Size(640, 520)
        MinimumSize = New Size(600, 480)
        StartPosition = FormStartPosition.CenterParent
        FormBorderStyle = FormBorderStyle.FixedDialog
        MaximizeBox = False
        MinimizeBox = False

        BuildLayout()
        PopulateGameList()
        ShowStep(1)
    End Sub


    ' ============================================================
    '  LAYOUT
    ' ============================================================

    Private Sub BuildLayout()
        ' ---- Step indicator ----
        _lblStepIndicator = New Label With {
            .Text = "Step 1 of 3",
            .Location = New Point(12, 12),
            .AutoSize = True,
            .ForeColor = Color.Gray
        }

        ' ---- Step 1: Game selection ----
        _pnlStep1 = New Panel With {
            .Location = New Point(0, 36),
            .Size = New Size(624, 390),
            .Visible = False
        }
        BuildStep1()

        ' ---- Step 2: Plugin config ----
        _pnlStep2 = New Panel With {
            .Location = New Point(0, 36),
            .Size = New Size(624, 390),
            .AutoScroll = True,
            .Visible = False
        }

        ' ---- Step 3: Review ----
        _pnlStep3 = New Panel With {
            .Location = New Point(0, 36),
            .Size = New Size(624, 390),
            .Visible = False
        }
        BuildStep3()

        ' ---- Navigation buttons ----
        Dim btnRow = ClientSize.Height - 44

        _btnCancel = New Button With {
            .Text = "Cancel",
            .Location = New Point(12, btnRow),
            .Size = New Size(88, 28),
            .DialogResult = DialogResult.Cancel
        }

        _btnBack = New Button With {
            .Text = "< Back",
            .Location = New Point(ClientSize.Width - 208, btnRow),
            .Size = New Size(88, 28),
            .Enabled = False
        }
        AddHandler _btnBack.Click, AddressOf OnBackClick

        _btnNext = New Button With {
            .Text = "Next >",
            .Location = New Point(ClientSize.Width - 112, btnRow),
            .Size = New Size(88, 28)
        }
        AddHandler _btnNext.Click, AddressOf OnNextClick

        AcceptButton = _btnNext
        CancelButton = _btnCancel

        Controls.AddRange({_lblStepIndicator,
                            _pnlStep1, _pnlStep2, _pnlStep3,
                            _btnCancel, _btnBack, _btnNext})
    End Sub

    Private Sub BuildStep1()
        Dim lblGame As New Label With {
            .Text = "Select game:",
            .Location = New Point(12, 8),
            .AutoSize = True,
            .Font = New Font(Font.FontFamily, 9, FontStyle.Bold)
        }

        _lstGames = New ListBox With {
            .Location = New Point(12, 28),
            .Size = New Size(590, 120),
            .BorderStyle = BorderStyle.FixedSingle
        }
        AddHandler _lstGames.SelectedIndexChanged, AddressOf OnGameSelected

        Dim lblName As New Label With {
            .Text = "Display name:",
            .Location = New Point(12, 162),
            .AutoSize = True
        }
        _txtDisplayName = New TextBox With {
            .Location = New Point(140, 160),
            .Size = New Size(460, 23),
            .PlaceholderText = "e.g. My Last Oasis Realm"
        }

        Dim lblPath As New Label With {
            .Text = "Install path on node:",
            .Location = New Point(12, 198),
            .AutoSize = True
        }
        _txtInstallPath = New TextBox With {
            .Location = New Point(140, 196),
            .Size = New Size(410, 23),
            .PlaceholderText = "e.g. C:\GameServers\LastOasis"
        }
        _btnBrowsePath = New Button With {
            .Text = "…",
            .Location = New Point(556, 196),
            .Size = New Size(36, 23),
            .FlatStyle = FlatStyle.Flat
        }
        AddHandler _btnBrowsePath.Click, AddressOf OnBrowsePathClick

        Dim lblMethod As New Label With {
            .Text = "Install method:",
            .Location = New Point(12, 234),
            .AutoSize = True
        }
        _cboInstallMethod = New ComboBox With {
            .Location = New Point(140, 232),
            .Size = New Size(200, 23),
            .DropDownStyle = ComboBoxStyle.DropDownList
        }

        _pnlStep1.Controls.AddRange({
            lblGame, _lstGames,
            lblName, _txtDisplayName,
            lblPath, _txtInstallPath, _btnBrowsePath,
            lblMethod, _cboInstallMethod
        })
    End Sub

    Private Sub BuildStep3()
        Dim lbl As New Label With {
            .Text = "Review your installation settings:",
            .Location = New Point(12, 8),
            .AutoSize = True,
            .Font = New Font(Font.FontFamily, 9, FontStyle.Bold)
        }

        _txtReview = New RichTextBox With {
            .Location = New Point(12, 28),
            .Size = New Size(590, 280),
            .ReadOnly = True,
            .BackColor = SystemColors.ControlLight,
            .BorderStyle = BorderStyle.FixedSingle
        }

        _chkInstallNow = New CheckBox With {
            .Text = "Start installation immediately after creating",
            .Location = New Point(12, 320),
            .AutoSize = True,
            .Checked = True
        }

        _pnlStep3.Controls.AddRange({lbl, _txtReview, _chkInstallNow})
    End Sub


    ' ============================================================
    '  GAME LIST
    ' ============================================================

    Private Sub PopulateGameList()
        Dim plugins = _pluginRegistry.GetAllPlugins()
        For Each plugin In plugins.OrderBy(Function(p) p.DisplayName)
            _lstGames.Items.Add(New PluginListItem(plugin))
        Next

        If _lstGames.Items.Count = 0 Then
            _lstGames.Items.Add("(No plugins loaded — use Plugins → Reload Plugins)")
        End If
    End Sub

    Private Sub OnGameSelected(sender As Object, e As EventArgs)
        Dim item = TryCast(_lstGames.SelectedItem, PluginListItem)
        If item Is Nothing Then Return

        _selectedPlugin = item.Plugin
        _txtDisplayName.PlaceholderText = $"e.g. My {_selectedPlugin.DisplayName} Server"

        ' Populate install method dropdown from plugin declaration.
        _cboInstallMethod.Items.Clear()
        For Each method In _selectedPlugin.GetSupportedInstallMethods()
            _cboInstallMethod.Items.Add(method.ToString())
        Next
        If _cboInstallMethod.Items.Count > 0 Then
            _cboInstallMethod.SelectedIndex = 0
        End If
    End Sub

    Private Sub OnBrowsePathClick(sender As Object, e As EventArgs)
        ' In a real implementation this would open a node path browser
        ' by calling GET /api/v1/system/drives and /api/v1/system/info
        ' on the target node and letting the user navigate the filesystem.
        ' For now we just use a local folder browser as a placeholder.
        Using dlg As New FolderBrowserDialog()
            dlg.Description = "Select install directory on the node"
            dlg.SelectedPath = _txtInstallPath.Text
            If dlg.ShowDialog() = DialogResult.OK Then
                _txtInstallPath.Text = dlg.SelectedPath
            End If
        End Using
    End Sub


    ' ============================================================
    '  WIZARD NAVIGATION
    ' ============================================================

    Private Sub ShowStep(stepNumber As Integer)
        _currentStep = stepNumber
        _lblStepIndicator.Text = $"Step {stepNumber} of {TotalSteps}"

        _pnlStep1.Visible = (stepNumber = 1)
        _pnlStep2.Visible = (stepNumber = 2)
        _pnlStep3.Visible = (stepNumber = 3)

        _btnBack.Enabled = stepNumber > 1
        _btnNext.Text = If(stepNumber = TotalSteps, "Create", "Next >")
    End Sub

    Private Sub OnBackClick(sender As Object, e As EventArgs)
        ShowStep(_currentStep - 1)
    End Sub

    Private Sub OnNextClick(sender As Object, e As EventArgs)
        Select Case _currentStep
            Case 1
                If Not ValidateStep1() Then Return
                BuildStep2()
                ShowStep(2)

            Case 2
                If Not ValidateStep2() Then Return
                BuildReview()
                ShowStep(3)

            Case 3
                CreateInstallation()
        End Select
    End Sub


    ' ============================================================
    '  STEP VALIDATION
    ' ============================================================

    Private Function ValidateStep1() As Boolean
        If _selectedPlugin Is Nothing Then
            MessageBox.Show("Please select a game.", "Validation",
                MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return False
        End If
        If String.IsNullOrWhiteSpace(_txtDisplayName.Text) Then
            MessageBox.Show("Please enter a display name.", "Validation",
                MessageBoxButtons.OK, MessageBoxIcon.Warning)
            _txtDisplayName.Focus()
            Return False
        End If
        If String.IsNullOrWhiteSpace(_txtInstallPath.Text) Then
            MessageBox.Show("Please enter the install path on the node.", "Validation",
                MessageBoxButtons.OK, MessageBoxIcon.Warning)
            _txtInstallPath.Focus()
            Return False
        End If
        Return True
    End Function

    Private Function ValidateStep2() As Boolean
        If _schemaBuilder Is Nothing Then Return True
        Dim errorMsg As String = Nothing
        If Not _schemaBuilder.IsValid(errorMsg) Then
            MessageBox.Show(errorMsg, "Validation",
                MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return False
        End If
        Return True
    End Function


    ' ============================================================
    '  STEP 2: PLUGIN CONFIG FORM (GENERATED)
    ' ============================================================

    Private Sub BuildStep2()
        _pnlStep2.Controls.Clear()

        If _selectedPlugin Is Nothing Then Return

        Dim schema = _selectedPlugin.GetInstallationConfigSchema()

        If Not schema.Any() Then
            ' This game has no installation config beyond what step 1 gathered.
            Dim lbl As New Label With {
                .Text = $"{_selectedPlugin.DisplayName} has no additional installation settings.",
                .Dock = DockStyle.Fill,
                .TextAlign = ContentAlignment.MiddleCenter,
                .ForeColor = Color.Gray
            }
            _pnlStep2.Controls.Add(lbl)
            _schemaBuilder = Nothing
            Return
        End If

        Dim header As New Label With {
            .Text = $"{_selectedPlugin.DisplayName} installation settings:",
            .Location = New Point(8, 8),
            .AutoSize = True,
            .Font = New Font(Font.FontFamily, 9, FontStyle.Bold)
        }
        _pnlStep2.Controls.Add(header)

        ' SchemaFormBuilder generates controls from the plugin's schema.
        _schemaBuilder = New SchemaFormBuilder(
            schema, "{}",
            _credentialService,
            _pluginRegistry)

        Dim schemaPanel = _schemaBuilder.BuildPanel()
        schemaPanel.Location = New Point(0, 32)
        schemaPanel.Width = _pnlStep2.Width
        _pnlStep2.Controls.Add(schemaPanel)
    End Sub


    ' ============================================================
    '  STEP 3: REVIEW
    ' ============================================================

    Private Sub BuildReview()
        _txtReview.Clear()

        _txtReview.AppendText($"Game:           {_selectedPlugin.DisplayName}{vbNewLine}")
        _txtReview.AppendText($"Display name:   {_txtDisplayName.Text}{vbNewLine}")
        _txtReview.AppendText($"Install path:   {_txtInstallPath.Text}{vbNewLine}")
        _txtReview.AppendText($"Install method: {_cboInstallMethod.SelectedItem}{vbNewLine}")
        _txtReview.AppendText(vbNewLine)

        If _schemaBuilder IsNot Nothing Then
            Dim configJson = _schemaBuilder.GetCurrentJson()
            _txtReview.AppendText("Installation config:" & vbNewLine)
            ' Pretty-print key/value pairs from the JSON.
            Try
                Dim doc = System.Text.Json.JsonDocument.Parse(configJson)
                For Each prop In doc.RootElement.EnumerateObject()
                    Dim val = prop.Value.ToString()
                    ' Mask sensitive fields.
                    Dim field = _selectedPlugin.GetInstallationConfigSchema().
                        FirstOrDefault(Function(f) f.Key = prop.Name)
                    If field?.IsSensitive = True AndAlso
                       Not String.IsNullOrEmpty(val) Then
                        val = New String("●"c, 8)
                    End If
                    _txtReview.AppendText($"  {prop.Name}: {val}{vbNewLine}")
                Next
            Catch
                _txtReview.AppendText(configJson)
            End Try
        End If
    End Sub


    ' ============================================================
    '  CREATE
    ' ============================================================

    Private Sub CreateInstallation()
        _btnNext.Enabled = False
        _btnBack.Enabled = False

        Dim pluginConfig = If(_schemaBuilder IsNot Nothing,
                               _schemaBuilder.GetCurrentJson(), "{}")

        Dim methodStr = If(_cboInstallMethod.SelectedItem?.ToString(), "SteamCMD")

        Dim entity As New InstallationEntity With {
            .DisplayName = _txtDisplayName.Text.Trim(),
            .GameId = _selectedPlugin.GameId,
            .NodeId = _nodeId,
            .InstallPath = _txtInstallPath.Text.Trim(),
            .InstallMethod = methodStr,
            .PluginConfig = pluginConfig,
            .IsEnabled = True,
            .LockState = "None"
        }

        Task.Run(Async Function()
                     Try
                         Dim created = Await _installationManager.CreateInstallationAsync(
                             entity, CancellationToken.None)

                         If _chkInstallNow.Checked Then
                             Await _installationManager.StartInstallAsync(
                                 created.InstallationId, CancellationToken.None)
                         End If

                         BeginInvoke(Sub()
                                         CreatedInstallationId = created.InstallationId
                                         DialogResult = DialogResult.OK
                                         Close()
                                     End Sub)

                     Catch ex As Exception
                         Dim errMsg = "Failed to create installation:" & vbNewLine & ex.Message
                         BeginInvoke(Sub()
                                         _btnNext.Enabled = True
                                         _btnBack.Enabled = True
                                         MessageBox.Show(
                                             errMsg,
                                             "Error",
                                             MessageBoxButtons.OK,
                                             MessageBoxIcon.Error)
                                     End Sub)
                     End Try
                 End Function)
    End Sub


    ' ============================================================
    '  HELPER TYPES
    ' ============================================================

    Private Class PluginListItem
        Public ReadOnly Property Plugin As IGamePlugin
        Public Sub New(plugin As IGamePlugin)
            Me.Plugin = plugin
        End Sub
        Public Overrides Function ToString() As String
            Return Plugin.DisplayName
        End Function
    End Class

End Class
