' <auto-generated />
Imports System
Imports GSM.Manager.Data
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic

Namespace Global.Migrations
    <DbContext(GetType(GsmDbContext))>
    <Migration("20260601194236_Phase5k_PlayerListPanel")>
    Partial Class Phase5k_PlayerListPanel
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2")

            modelBuilder.Entity("GSM.Manager.Data.AppSettingEntity",
                Sub(b)
                    b.Property(Of String)("SettingKey").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("Value").
                        HasMaxLength(4000).
                        HasColumnType("TEXT")

                    b.HasKey("SettingKey")

                    b.ToTable("AppSettings")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.AutomationRuleEntity",
                Sub(b)
                    b.Property(Of String)("RuleId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ActionJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ConditionsJson").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("GameFilter").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("IsEnabled").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("RuleName").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of String)("ScopeKind").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("SortOrder").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("TargetId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("TriggerJson").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("RuleId")

                    b.HasIndex("SortOrder")

                    b.ToTable("AutomationRules")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.ChatMessageEntity",
                Sub(b)
                    b.Property(Of String)("MessageId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CharacterId").
                        HasMaxLength(64).
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstanceId").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("NodeId").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("PlatformUserId").
                        HasMaxLength(64).
                        HasColumnType("TEXT")

                    b.Property(Of String)("SessionIdentity").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of String)("Text").
                        HasMaxLength(4000).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("TimestampUtc").
                        HasColumnType("TEXT")

                    b.HasKey("MessageId")

                    b.HasIndex("CharacterId")

                    b.HasIndex("TimestampUtc")

                    b.HasIndex("SessionIdentity", "TimestampUtc")

                    b.ToTable("ChatMessages")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.DiscordBotConfigEntity",
                Sub(b)
                    b.Property(Of String)("ConfigId").
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("Enabled").
                        HasColumnType("INTEGER")

                    b.Property(Of Byte())("EncryptedToken").
                        HasColumnType("BLOB")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("ConfigId")

                    b.ToTable("DiscordBotConfigs")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.DiscordPanelEntity",
                Sub(b)
                    b.Property(Of String)("PanelId").
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of String)("ChannelId").
                        IsRequired().
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("GroupingKind").
                        IsRequired().
                        HasMaxLength(40).
                        HasColumnType("TEXT")

                    b.Property(Of String)("GuildId").
                        IsRequired().
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of String)("LayoutJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("MessageId").
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of String)("PanelKind").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(40).
                        HasColumnType("TEXT").
                        HasDefaultValue("InstanceManager")

                    b.Property(Of Integer)("RefreshIntervalSeconds").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("ScopeKind").
                        IsRequired().
                        HasMaxLength(40).
                        HasColumnType("TEXT")

                    b.Property(Of String)("ScopeTargetId").
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("ShowEmptyGroups").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER").
                        HasDefaultValue(False)

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("PanelId")

                    b.HasIndex("GuildId")

                    b.ToTable("DiscordPanels")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.DiscordRoleMappingEntity",
                Sub(b)
                    b.Property(Of String)("GuildId").
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of String)("PanelId").
                        ValueGeneratedOnAdd().
                        HasMaxLength(64).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.Property(Of String)("RoleId").
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("Permission").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("RoleName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("GuildId", "PanelId", "RoleId")

                    b.ToTable("DiscordRoleMappings")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.InstallationEntity",
                Sub(b)
                    b.Property(Of String)("InstallationId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ConfigJson").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        HasColumnType("TEXT")

                    b.Property(Of String)("GameId").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstallMethod").
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstallPath").
                        IsRequired().
                        HasMaxLength(1000).
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstalledVersion").
                        HasColumnType("TEXT")

                    b.Property(Of Date?)("LastVersionCheckUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("LatestKnownVersion").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("MaxConcurrentRestarts").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("NodeId").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("RunCommonRedist").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("SharedConfigGroupId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("SteamCredentialId").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("InstallationId")

                    b.HasIndex("NodeId")

                    b.HasIndex("SharedConfigGroupId")

                    b.ToTable("Installations")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.InstanceEntity",
                Sub(b)
                    b.Property(Of String)("InstanceId").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("AutoStart").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("ConfigJson").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ExeOverride").
                        HasColumnType("TEXT")

                    b.Property(Of String)("GameId").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstallationId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstanceSetTag").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("RestartCron").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("RestartEnabled").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("RestartRuleId").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("SortOrder").
                        HasColumnType("INTEGER")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("InstanceId")

                    b.HasIndex("InstanceSetTag")

                    b.HasIndex("InstallationId", "SortOrder")

                    b.ToTable("Instances")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.NodeEntity",
                Sub(b)
                    b.Property(Of String)("NodeId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("AuthToken").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of String)("HostAddress").
                        IsRequired().
                        HasMaxLength(500).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("IsEnabled").
                        HasColumnType("INTEGER")

                    b.Property(Of Integer?)("LastSeenProtocolVersion").
                        HasColumnType("INTEGER")

                    b.Property(Of Date)("LastSeenUtc").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("MaxConcurrentRestarts").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("OsDescription").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("Port").
                        HasColumnType("INTEGER")

                    b.HasKey("NodeId")

                    b.ToTable("Nodes")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.NotificationDestinationEntity",
                Sub(b)
                    b.Property(Of String)("DestinationId").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("Enabled").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("EnabledEventTypesJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstallationFilterJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstanceFilterJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("TemplateOverridesJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("TransportConfigJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("TransportKind").
                        IsRequired().
                        HasMaxLength(40).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("VisibilityProfileId").
                        HasColumnType("TEXT")

                    b.HasKey("DestinationId")

                    b.HasIndex("Enabled")

                    b.ToTable("NotificationDestinations")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.NotificationPluginEntity",
                Sub(b)
                    b.Property(Of String)("PluginId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ConfigJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("IsEnabled").
                        HasColumnType("INTEGER")

                    b.HasKey("PluginId")

                    b.ToTable("NotificationPlugins")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.NotificationSubscriptionEntity",
                Sub(b)
                    b.Property(Of String)("SubscriptionId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("EventName").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("IsEnabled").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("PluginId").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("RoutingHintsJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ScopeKind").
                        HasColumnType("TEXT")

                    b.Property(Of String)("TargetId").
                        HasColumnType("TEXT")

                    b.HasKey("SubscriptionId")

                    b.ToTable("NotificationSubscriptions")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.PlayerActivityEntity",
                Sub(b)
                    b.Property(Of String)("ActivityId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CharacterId").
                        HasMaxLength(64).
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("EventKind").
                        IsRequired().
                        HasMaxLength(20).
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstanceId").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("NodeId").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("PlatformUserId").
                        HasMaxLength(64).
                        HasColumnType("TEXT")

                    b.Property(Of String)("PlayerName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("SessionIdentity").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("TimestampUtc").
                        HasColumnType("TEXT")

                    b.HasKey("ActivityId")

                    b.HasIndex("CharacterId")

                    b.HasIndex("PlayerName", "TimestampUtc")

                    b.HasIndex("SessionIdentity", "TimestampUtc")

                    b.ToTable("PlayerActivity")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.PlayerSessionEntity",
                Sub(b)
                    b.Property(Of String)("PlayerSessionId").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("FirstSeenUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("LastHostInstanceId").
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("LastSeenUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("PlayerName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("SessionIdentity").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.HasKey("PlayerSessionId")

                    b.HasIndex("SessionIdentity", "LastSeenUtc")

                    b.HasIndex("SessionIdentity", "PlayerName").
                        IsUnique()

                    b.ToTable("PlayerSessions")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.RuleExecutionEntity",
                Sub(b)
                    b.Property(Of String)("ExecutionId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ActionResultJson").
                        HasColumnType("TEXT")

                    b.Property(Of Date?)("CompletedAtUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ConditionResultsJson").
                        HasColumnType("TEXT")

                    b.Property(Of String)("RuleId").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("SkipReason").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("StartedAtUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("TriggerReason").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("WasSkipped").
                        HasColumnType("INTEGER")

                    b.HasKey("ExecutionId")

                    b.HasIndex("RuleId")

                    b.HasIndex("StartedAtUtc")

                    b.ToTable("RuleExecutions")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.SessionHostEntity",
                Sub(b)
                    b.Property(Of String)("HostId").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("HostedFromUtc").
                        HasColumnType("TEXT")

                    b.Property(Of Date?)("HostedUntilUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstanceId").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of String)("SessionIdentity").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of String)("TileName").
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.HasKey("HostId")

                    b.HasIndex("InstanceId", "HostedUntilUtc")

                    b.HasIndex("SessionIdentity", "HostedFromUtc")

                    b.ToTable("SessionHosts")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.SharedConfigGroupEntity",
                Sub(b)
                    b.Property(Of String)("GroupId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("ConfigJson").
                        IsRequired().
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.Property(Of String)("GroupType").
                        IsRequired().
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of String)("PluginId").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("GroupId")

                    b.HasIndex("PluginId", "GroupType")

                    b.ToTable("SharedConfigGroups")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.SteamCredentialEntity",
                Sub(b)
                    b.Property(Of String)("CredentialId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        HasColumnType("TEXT")

                    b.Property(Of Byte())("EncryptedPassword").
                        HasColumnType("BLOB")

                    b.Property(Of Boolean)("IsAnonymous").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Username").
                        IsRequired().
                        HasMaxLength(200).
                        HasColumnType("TEXT")

                    b.HasKey("CredentialId")

                    b.ToTable("SteamCredentials")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.VisibilityProfileEntity",
                Sub(b)
                    b.Property(Of String)("ProfileId").
                        HasColumnType("TEXT")

                    b.Property(Of String)("AllowedFieldsJson").
                        HasColumnType("TEXT")

                    b.Property(Of Date)("CreatedUtc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("DisplayName").
                        IsRequired().
                        HasMaxLength(100).
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("IsBuiltIn").
                        HasColumnType("INTEGER")

                    b.Property(Of Date)("UpdatedUtc").
                        HasColumnType("TEXT")

                    b.HasKey("ProfileId")

                    b.ToTable("VisibilityProfiles")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.InstallationEntity",
                Sub(b)
                    b.HasOne("GSM.Manager.Data.NodeEntity", "Node").
                        WithMany("Installations").
                        HasForeignKey("NodeId")

                    b.HasOne("GSM.Manager.Data.SharedConfigGroupEntity", "SharedConfigGroup").
                        WithMany("Installations").
                        HasForeignKey("SharedConfigGroupId")
                    b.Navigation("Node")

                    b.Navigation("SharedConfigGroup")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.InstanceEntity",
                Sub(b)
                    b.HasOne("GSM.Manager.Data.InstallationEntity", "Installation").
                        WithMany("Instances").
                        HasForeignKey("InstallationId")
                    b.Navigation("Installation")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.InstallationEntity",
                Sub(b)
                    b.Navigation("Instances")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.NodeEntity",
                Sub(b)
                    b.Navigation("Installations")
                End Sub)

            modelBuilder.Entity("GSM.Manager.Data.SharedConfigGroupEntity",
                Sub(b)
                    b.Navigation("Installations")
                End Sub)
        End Sub
    End Class
End Namespace
